### PR TITLE
removed tslint and pg-types

### PR DESCRIPTION
**Pull request by deepakprabhakara**
Thank you for contributing to Retraced!

# Please add a summary of your change

# Does your change fix a particular issue?

Fixes #(issue)

### CODE REVIEW

**Comment by deepakprabhakara** [comment]
@ukrocks007 If you add back pg-types does the error go away?

**Comment by ukrocks007** [comment]
> @ukrocks007 If you add back pg-types does the error go away?

yes it goes away

**Comment by deepakprabhakara** [comment]
https://www.npmjs.com/package/pg-types is the new lib, need to figure out how to migrate to it. `@types/pg-types` is deprecated.

**Comment by deepakprabhakara** [comment]
@ukrocks007 I am unable to reproduce the error you are seeing

**Comment by ukrocks007** [comment]
> @ukrocks007 I am unable to reproduce the error you are seeing

I built from scratch by deleting all the images and saw the logs of processor & I got this

```
@instrumented decorator processing ElasticsearchSaver.esIndex
@instrumented decorator processing Emailer.send
@instrumented decorator processing ElasticsearchIndexRotator.getEnvironments
@instrumented decorator processing ElasticsearchIndexRotator.verifyIndexAliases
@instrumented decorator processing ElasticsearchIndexRotator.appendNewIndex
Anonymous analytics enabled. You can disable this by setting the DO_NOT_TRACK=1 or RETRACED_NO_ANALYTICS=1 environment variables
{"level":50,"time":1679040630751,"pid":1,"hostname":"9f827f240a7b","msg":"BUGSNAG_TOKEN not set, error reports will not be sent to bugsnag"}
PG_SEARCH not set, using ElasticSearch
{"level":50,"time":1679040630759,"pid":1,"hostname":"9f827f240a7b","msg":"neither KUBERNETES_SERVICE_HOST nor STATSD_HOST is set, metrics will not be reported to statsd or sysdig"}
{"level":50,"time":1679040630759,"pid":1,"hostname":"9f827f240a7b","msg":"STATUSPAGEIO_TOKEN not set, metrics will not be reported to statuspage.io"}
/app/node_modules/pg-protocol/src/parser.ts:369
      name === 'notice' ? new NoticeMessage(length, messageValue) : new DatabaseError(messageValue, length, name)
                                                                    ^


error: relation "environment" does not exist
    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 110,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '15',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1381',
  routine: 'parserOpenTable'
}
```

After that I restarted the container and saw logs and the error was gone

```
Node.js v18.14.2
Debugger listening on ws://0.0.0.0:9229/c4c8fd93-7286-4d58-9ad9-f4537da1d075
For help, see: https://nodejs.org/en/docs/inspector
@instrumented decorator processing ElasticsearchSaver.esIndex
@instrumented decorator processing Emailer.send
@instrumented decorator processing ElasticsearchIndexRotator.getEnvironments
@instrumented decorator processing ElasticsearchIndexRotator.verifyIndexAliases
@instrumented decorator processing ElasticsearchIndexRotator.appendNewIndex
Anonymous analytics enabled. You can disable this by setting the DO_NOT_TRACK=1 or RETRACED_NO_ANALYTICS=1 environment variables
{"level":50,"time":1679040639736,"pid":1,"hostname":"9f827f240a7b","msg":"BUGSNAG_TOKEN not set, error reports will not be sent to bugsnag"}
PG_SEARCH not set, using ElasticSearch
{"level":50,"time":1679040639738,"pid":1,"hostname":"9f827f240a7b","msg":"neither KUBERNETES_SERVICE_HOST nor STATSD_HOST is set, metrics will not be reported to statsd or sysdig"}
{"level":50,"time":1679040639738,"pid":1,"hostname":"9f827f240a7b","msg":"STATUSPAGEIO_TOKEN not set, metrics will not be reported to statuspage.io"}
Debugger listening on ws://0.0.0.0:9229/afc577c3-b4de-474e-9d56-994c7df10ecc
For help, see: https://nodejs.org/en/docs/inspector
@instrumented decorator processing ElasticsearchSaver.esIndex
@instrumented decorator processing Emailer.send
@instrumented decorator processing ElasticsearchIndexRotator.getEnvironments
@instrumented decorator processing ElasticsearchIndexRotator.verifyIndexAliases
@instrumented decorator processing ElasticsearchIndexRotator.appendNewIndex
Anonymous analytics enabled. You can disable this by setting the DO_NOT_TRACK=1 or RETRACED_NO_ANALYTICS=1 environment variables
{"level":50,"time":1679040692637,"pid":1,"hostname":"9f827f240a7b","msg":"BUGSNAG_TOKEN not set, error reports will not be sent to bugsnag"}
PG_SEARCH not set, using ElasticSearch
{"level":50,"time":1679040692637,"pid":1,"hostname":"9f827f240a7b","msg":"neither KUBERNETES_SERVICE_HOST nor STATSD_HOST is set, metrics will not be reported to statsd or sysdig"}
{"level":50,"time":1679040692637,"pid":1,"hostname":"9f827f240a7b","msg":"STATUSPAGEIO_TOKEN not set, metrics will not be reported to statuspage.io"}
```

Looks like processor tried to access the tables before they got created in db.

**Review by ukrocks007 — APPROVED** [review]

**Pull request merged**
